### ISSUE TITLE
有设置可以启用键盘方向键吗？期望有一个类似的设置

### ISSUE THREAD

**Issue by TqLj** [javaLuo/vue-ohyeah-scroll#1]
有设置可以启用键盘方向键吗？期望有一个类似的设置。
空格滚动一屏幕
上下方向键滚动几行

**Comment by javaLuo** [comment]
没问题，我来研究研究

**Comment by TqLj** [comment]
对了，方向键滚动，记得要先判断下当前焦点是不是在textarea或者input，如果是，就忽略事件，这一个坑。

**Comment by javaLuo** [comment]
👌ok

**Comment by javaLuo** [comment]
hi,我更新了`0.4.0`版本

```
<Ohyeah
    useKeybord // 开启键盘方向键控制
    :movePx="160" // 按键一次，页面滚动的距离，单位px
>
...
</Ohyeah>
```

我只在mac上测了一下，待我回去再仔细测测

**Comment by TqLj** [comment]
@javaLuo 测试了一下，上下可以了，但是空格没有滚动一屏幕（你可以测试下chrome的默认行为，空格会滚动一屏幕）

**Comment by TqLj** [comment]
```
      e.preventDefault(); // 需要这个，不然外部原生滚动条也会跟着滚动
      e.stopImmediatePropagation();
```
这两句有很大的问题，我绑定的其他事件（比如esc）也没了，ctrl+r也不能刷新页面了

正确的做法是当且仅当为方向键、空格，并且不是textarea、input的时候才执行      e.preventDefault();
      e.stopImmediatePropagation();

**Comment by TqLj** [comment]
stopImmediatePropagation 这个是不是可以考虑去掉？
