### ISSUE TITLE
bug：当页面上有页内锚点，点击会重新定位，但是滚动条没有跟着调整位置

### ISSUE THREAD

**Issue by TqLj** [javaLuo/vue-ohyeah-scroll#3]
如题

**Comment by javaLuo** [comment]
我决定重构这个组件
完全模拟原生滚动条的功能貌似坑有点多。
我打算隐藏原生滚动条但保持滚动条的可滚动性，然后用div模拟一个滑块

**Comment by TqLj** [comment]
期待，正在基于这个开发一个静态博客

**Comment by javaLuo** [comment]
我发布了重构后的版本
现在可以正常跳转锚点了。
平滑滚动用的scroll-behavior:smooth;
所以只有chrome/firefox/opera 锚点跳转的时候能平滑过度

**Comment by TqLj** [comment]
完美
