### ISSUE TITLE
0.54版多了一个div，是必须的吗，可以去掉吗？（影响原来的样式，我是用的>选择器）

### ISSUE THREAD

**Issue by TqLj** [javaLuo/vue-ohyeah-scroll#4]
![image](https://user-images.githubusercontent.com/52188840/66976572-f96e5000-f0d4-11e9-884c-509a1ccf845b.png)
0.54版多了一个div，是必须的吗，可以去掉吗？（影响原来的样式，我是用的>选择器），如果不能去掉，能不能给div加一个class，方便精确定位

**Comment by javaLuo** [comment]
额，这个必须要，为了监听内容高度变化
ohyeah-scroll-box 最外部容器，为了放两个绝对定位的滚动条
ohyeah-scroll-body 真正的滚动容器，window大小变化，它也会变
div 高度auto，内容增减会引起这个div大小变化，所以这个不好去掉额

不过我想想看有没有优化的方法

**Comment by javaLuo** [comment]
我先加一个class吧

**Comment by javaLuo** [comment]
我加了一个`ohyeah-scroll-content`

**Comment by TqLj** [comment]
好 , 多谢
